### ISSUE TITLE
ok() is usually exported by test tools

### ISSUE THREAD

**Issue by mjgardner** [tobyink/p5-results#1]
I blinked when I saw the [`ok()`](https://metacpan.org/pod/results#ok()) function, as that's usually claimed by test frameworks/tools like [Test::Simple](https://metacpan.org/pod/Test::Simple#ok), [Test::More](https://metacpan.org/pod/Test::More#ok), and [Test2::Suite](https://metacpan.org/pod/Test2::Suite)'s [Test2::Tools::Basic](https://metacpan.org/pod/Test2::Tools::Basic#ok($bool)). While the latter can [omit or rename imports](https://metacpan.org/pod/Test2::V0#RENAMING-ON-IMPORT), the others don't, and also I think it violates the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) to use a canonically well-established function name for a different purpose.

I realize you need a short and immediately obvious name for an often-used function that is fundamental to this module, and Rust already calls its [Results](https://doc.rust-lang.org/std/result/) `Ok` and `Err`. And we all know that naming things is a Hard CS Problem. But I think this pragma might want to live in test scripts as well as regular programs, so it should play nice with the modules already there.

**Comment by tobyink** [comment]
Yeah, it did annoy me writing tests.

I considered `Ok` and `Err`, but it's also conventional for functions, especially keyword-like functions, to be lowercase in Perl.

Likely I'll just document patterns like omitting imports:

```perl
use results ();

...

return results::ok( 42 );
```

And renaming imports:

```perl
use results { suffix => '_R' };

...

return ok_R( 42 );
```

Maybe even properly document that `Result::Ok->new(...)` works.

And mention that they may be especially useful in test scripts.

That said, I would expect test scripts to be more likely to have to *handle* Result objects rather than *create* them, in which case they don't need to import anything.

**Comment by tobyink** [comment]
This should also work, if you either have bleeding-edge Perl 5.37.2+ or have Lexical::Sub installed:

```perl
use Test::More;

sub my_func {
  use results -lexical;
  ...;
  return ok( 42 );
}
```

**Comment by mjgardner** [comment]
I’m fine with the docs as the “fix.”
